In [40]:
# import pandas as pd

# print('Pandas version:', pd.__version__)

#### Task 1 : Pandas Series Basics

In [30]:
import pandas as pd

marks = pd.Series([78,85,90,66,72])

# print values
marks

0    78
1    85
2    90
3    66
4    72
dtype: int64

In [31]:
# print index
marks.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
# print data type
marks.dtype

dtype('int64')

In [33]:

# access first element
marks[0]

np.int64(78)

In [34]:
# acess last two elemets
# print(marks[-2:])
marks.tail(2)

3    66
4    72
dtype: int64


#### Task 2: Mathematical Operation on Series

In [ ]:
# 1. add 5 grace marks to all students
marks + 5

0    83
1    90
2    95
3    71
4    77
dtype: int64

In [ ]:

# 2. substract 2 marks from all values
marks - 2

0    76
1    83
2    88
3    64
4    70
dtype: int64

In [ ]:
# 3. Multiply all marks by 1.05
marks * 1.05

0    81.90
1    89.25
2    94.50
3    69.30
4    75.60
dtype: float64

In [38]:
# 4. Divide all marks by 2
marks / 2

0    39.0
1    42.5
2    45.0
3    33.0
4    36.0
dtype: float64

#### Task 3: Python Functionalities on Series

In [41]:
# 1. Find maximum marks
marks.max()

90

In [42]:
# Minimum msrks
marks.min()

66

In [43]:
# Sum of marks
marks.sum()

np.int64(391)

In [44]:
# Mean marks
marks.mean()

np.float64(78.2)

In [ ]:
# 2. Apply a Lambda function to check weather each student has passed(>=70)
marks.apply(lambda x:x >=70)

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [48]:
# 3. Count how many students passed
(marks > 70).sum()

np.int64(4)

#### Task 4: Create a DataFrame

In [57]:
# Create a DataFrame students
students = {
    'Name':['Amit','Neha','Rahul','Sneha','Pooja'],
    'Marks':[78,85,90,66,72],
    'Subject':['Mth','Math','Science','Science','Math']
}
students

{'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Pooja'],
 'Marks': [78, 85, 90, 66, 72],
 'Subject': ['Mth', 'Math', 'Science', 'Science', 'Math']}

In [ ]:
# 1. convert into DataFrame
df_students = pd.DataFrame(students)
df_students

    Name  Marks  Subject
0   Amit     78      Mth
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [60]:
type(df_students)

pandas.core.frame.DataFrame

In [61]:
# 2. Print first rows
df_students.head(3)

    Name  Marks  Subject
0   Amit     78      Mth
1   Neha     85     Math
2  Rahul     90  Science

In [62]:
# 3. Print last 2 rows
df_students.tail(2)

    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

In [64]:
# 4. Print DataFrame shape and column name
df_students.shape

(5, 3)

In [ ]:
# Print DataFrame column name
df_students.columns

Index(['Name', 'Marks', 'Subject'], dtype='object')